version: '3.3'

services:
  mobile:
    tty: true
    build: 
      context: mobile-client
      dockerfile: Dockerfile
    ports:
      - 9080:80
    networks:
      - infra_tools
      
  adventureservice:
    tty: true
    build: 
      context: adventure-service
      dockerfile: Dockerfile
    ports:
      - 9899:9899
    restart: always
    networks:
      - infra_tools

  aiservice:
    tty: true
    build:
      context: ai-service
      dockerfile: Dockerfile
    ports:
      - 9799:9799
    restart: always
    networks:
      - infra_tools

  websocketservice:
    tty: true
    build:
      context: socket-service
      dockerfile: Dockerfile
    ports:
      - 9698:9698
    restart: always
    networks:
      - infra_tools

networks:
  infra_tools:
    external: true